### ISSUE TITLE
Which system predictions correspond to scores reported in the paper?

### ISSUE THREAD

**Issue by louismartin** [subramanyamdvss/UnsupNTS#5]
Hi,

Thanks for sharing your work.
Can you please indicate which of the prediction files correspond to which scores reported in the paper?

Prediction files I am talking about:
`gen_lower.sen.src2trg.wgan.onlyback.denoi.back1.singleclassf.rho1.0.10k.22000.test.noredund`
`gen_lower.sen.src2trg.wgan.semisup10k-sel-6-4.noadvcompl.control1.allclass.denoi.singleclassf.rho1.0.10k.10000.test.noredund`
`gen_lower.sen.src2trg.wgan.unsup.noadvcompl.control1.allclass.denoi.singleclassf.rho1.0.10k.13500.test.noredund`

Thank you for your help.

**Comment by saisuryadv** [comment]
gen_lower.sen.src2trg.wgan.onlyback.denoi.back1.singleclassf.rho1.0.10k.22000.test.noredund --> UNMT
gen_lower.sen.src2trg.wgan.semisup10k-sel-6-4.noadvcompl.control1.allclass.denoi.singleclassf.rho1.0.10k.10000.test.noredund --> UNTS+10K
gen_lower.sen.src2trg.wgan.unsup.noadvcompl.control1.allclass.denoi.singleclassf.rho1.0.10k.13500.test.noredund --> UNTS

The scores of UNTS, UNTS+10k, UNMT are in the paper.

Thanks for taking an interest.

**Comment by louismartin** [comment]
Ok great thanks !
Do you mind if I add them in the [EASSE](https://github.com/feralvam/easse/) library along with [other system outputs](https://github.com/feralvam/easse/tree/master/easse/resources/data/system_outputs/turkcorpus/test) ?

**Comment by louismartin** [comment]
Related PR: https://github.com/feralvam/easse/pull/56
