### ISSUE TITLE
the error when run the train.sh

### ISSUE THREAD

**Issue by monkdou0** [subramanyamdvss/UnsupNTS#6]
hello,  I meet this error when run the train.sh
![image](https://user-images.githubusercontent.com/68677162/100178066-2c0c8e00-2f0e-11eb-8d69-f32cd76b1419.png)
Can someone explain the reason,Thx!

**Comment by mlschomaker** [comment]
I have the same issue. I already tried to reduce the kernel sizes, but this does not solve the issue.

**Comment by mlschomaker** [comment]
@monkdou0 in the closed issues thread, someone had the same problem where the fix was to run the script in pytorch 0.3.1.
