### ISSUE TITLE
the dismatch between dataset and paper 

### ISSUE THREAD

**Issue by monkdou0** [subramanyamdvss/UnsupNTS#7]
the paper shows that there are 720k easy and hard sentences sepecifically,
but the download data has 2000000 row hard and 2000000 row easy sentences sepecifically(the file is tsdata/fkdifficpart-2m-1.lower and tsdata/fkeasycpart-2m-1.lower).
WHy?

![image](https://user-images.githubusercontent.com/68677162/102751830-7ebd5680-43a3-11eb-9022-1a7fa49645f9.png)

**Comment by saisuryadv** [comment]
Only first 720k sentences were used for training
