### ISSUE TITLE
document system and dependency requirements

### ISSUE THREAD

**Issue by scott2b** [subramanyamdvss/UnsupNTS#8]
Requirements are not documented. A requirements.txt file would be very helpful. Also, it appears that pytorch must be compiled with CUDA support, implying the need for CUDA at the system level.

Somewhat related to dependencies in general: the use of Spacy corpus shortcuts is obsolete. The corpus reference in similarity_scorer.py should be to a specific corpus rather than "en"

**Comment by saisuryadv** [comment]
To address your first question, yes, Pytorch with CUDA support is needed. Here are relevant links, [link1](https://discuss.pytorch.org/t/how-to-switch-to-older-version-of-pytorch/19656/3), [link2](https://discuss.pytorch.org/t/how-to-switch-to-older-version-of-pytorch/19656/5). We recommend running the code in Pytorch 0.3.1, however, this version seems to be compatible with up to CUDA version 9.0.

similarity_scorer.py has miscellaneous tools referenced only for debugging purposes, you can choose to uncomment the references, if you wish to only monitor standard losses. But if you are interested, I recommend running the code with older version of [spacy](https://pypi.org/project/spacy/2.0.15/).
